[[runners]]
  name = "Simple Docker in Docker"
  url = "https://gitlab.com/"
  executor = "docker"
  token = ""

  [runners.docker]
    # Required to run DinD services
    privileged = true

[[runners]]
  name = "Shared host Docker daemon"
  url = "https://gitlab.com/"
  executor = "docker"
  token = ""

  [runners.docker]
    
    # Volumes to mount in containers running CI jobs. Same syntax as the Docker -v flag. 
    volumes = [
        # Mount the Docker socket so we can use it in our build
        "/var/run/docker.sock:/var/run/docker.sock",
    ]

[[runners]]
  name = "Remote secured Docker daemon"
  url = "https://gitlab.com/"
  executor = "docker"
  token = ""

  # Environment variabmes available in containers running jobs
  # Will use our remote Docker Daemon using certificates mounted as volume
  environment = [
    "DOCKER_HOST=tcp://35.180.191.255:2376",
    "DOCKER_CERT_PATH=/certs/client",
    "DOCKER_TLS=1",
  ]

  [runners.docker]
    # Mount our client certificate in job's containers to authenticate with remote Docker daemon
    volumes = [
      "/media/pierre/Data/git/devops-examples/docker-build-ci-optimization/dockerd-tls/.tls/client/:/certs/client"
    ]