# Mix of Jinja2 and AWS templating
# Jinja2 templating is used only when absolutely necessary (i.e. for loops) and AWS templating is ued otherwise
# to pass all simple parameters and templating
AWSTemplateFormatVersion: 2010-09-09
Description: Deploys an EC2 instance with a Route53 DNS record allowing SSH and HTTP(S)
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

Resources:

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroup for Docker Daemon instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 2376
          ToPort: 2376
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.small
      KeyName: !Ref KeyName
      ImageId: ami-06d79c60d7454e2af # Ubuntu 20.04 eu-west-3
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
          - !GetAtt InstanceSecurityGroup.GroupId

Outputs:
  DockerdIP:
    Description: Hostname of DockerD instance
    Value: !GetAtt EC2Instance.PublicIp