name: example-app-mysql-hashivault

# Use our example Vault and AWS (Localstack) instances
# For real usage you're gonna use real instances
config:
  hashivault:
    address: http://localhost:8200
  aws:
    endpoint: "http://localhost:4566/"

environments:
  
  # Secrets for Staging environment
  dev:

    # Load secrets from Hashicorp Vault as environment variables
    variables:
      - name: NPM_TOKEN
        value: 
          hvault_kv2:
            path: app/dev
            key: npm_token
      - name: MYSQL_PASSWORD
        value: 
          hvault_kv2:
            path: app/dev
            key: mysql_password
      - name: MYSQL_USER
        value: root
    
    # Generate temporary AWS credentials for Role
    aws:
      assume_role:
        role_arn: arn:aws:iam::12345678910:role/dev_deploy

  # Secrets for Production environment
  prod:

    variables:
      - name: NPM_TOKEN
        value: 
          hvault_kv2:
            path: app/prod
            key: npm_token
      - name: MYSQL_PASSWORD
        value: 
          hvault_kv2:
            path: app/prod
            key: mysql_password
      - name: MYSQL_USER
        value: root

    aws:
      assume_role:
        role_arn: arn:aws:iam::12345678910:role/prod_deploy