
FROM node:17-alpine3.14

WORKDIR /app

# Copy package.json fles and install dependencies
# This may take a long time as your project grows
# Especially if running on CI or ephemeral environment
COPY package.json package-lock.json /app/
RUN npm install --frozen-lockfile --only=prod

# Copy remaining files and setup command
COPY . /app
CMD ["node", "index.js"]